# management.endpoint.web.exposure.include=*
spring:
  application:
    name: ecom-micro
  datasource:
    url: jdbc:postgresql://localhost:5432/ecom-microDB
    username: ecom-micro
    password: ecom-micro
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  datasource:
#    url: jdbc:h2:mem:test
#  h2:
#    console:
#      enabled: true
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

management:
  endpoints:
    web:
      exposure:
        include: '*' #example: beans, health....dont enable all, just select
    health:
      show-details: always #when-authorized #never
#    shutdown:
#      enabled: true #Be careful
  info:
    env:
      enabled: true

#server:
#  shutdown: graceful

info:
  app:
    name: MyApp
    description: App
    version: 1.1.1




